# Generated by Django 3.0.8 on 2020-07-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_audio_consoles_garden_tv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='garden',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tv',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
