# Generated by Django 3.0.8 on 2020-07-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200709_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='garden',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tv',
            name='price',
            field=models.FloatField(),
        ),
    ]
