# Generated by Django 3.0.7 on 2020-07-20 15:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200720_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='variantsNumber',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10),
        ),
    ]
