# Generated by Django 3.0.7 on 2020-07-20 19:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200720_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilesAndGudgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=4)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='mobilesAndGudgets', max_length=100)),
                ('price', models.FloatField()),
                ('article', models.CharField(max_length=100)),
                ('colorsStock', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10)),
                ('variantsNumber', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('screen', models.CharField(max_length=200)),
                ('camera', models.CharField(max_length=100)),
                ('batteryCapacity', models.CharField(max_length=200)),
            ],
        ),
    ]
