# Generated by Django 3.0.8 on 2020-07-08 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='clothes', max_length=100)),
                ('price', models.IntegerField()),
                ('article', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=200)),
                ('numbersOfPages', models.IntegerField()),
                ('coverBinding', models.CharField(max_length=20)),
                ('color_stock', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10)),
                ('variantsNumber', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10)),
            ],
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(default='clothes', max_length=100),
        ),
    ]
