# Generated by Django 3.0.8 on 2020-07-09 09:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200708_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=4),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=4),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=4),
        ),
        migrations.AlterField(
            model_name='garden',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=4),
        ),
        migrations.AlterField(
            model_name='tv',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=4),
        ),
    ]
